### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by klokan** [klokan/osm-vector-offline#3]
Next step is to be able to compile the app for offline mode.

It means to pack the MBTiles into the app - and include offline all the style and related resource like fonts, icons, etc.

This is under active development on MapBox GL Native still:

https://github.com/mapbox/mapbox-gl-native/issues/584

https://github.com/mapbox/mapbox-gl-native/issues/1901
https://github.com/mapbox/mapbox-gl-native/pull/2939

https://github.com/mapbox/mapbox-gl-native/pull/1635 (deprecated)
https://github.com/mapbox/mapbox-gl-native/issues/1048

**Comment by klokan** [comment]
Now possible with latest MapBox GL (selecting an area of interest and caching the tiles locally).

Running against custom URL with tiles (such as hosted OSM2VectorTIles) is possible too - tested in https://github.com/klokantech/osm2vectortiles-ios

We work on in-app MBTiles loading.

**Comment by klokan** [comment]
Offline MBTiles loading is now implemented.

Get the free OSM2VectorTiles app from Android & iOS stores.

**Comment by o15a3d4l11s2** [comment]
@klokan, is there a way to render a mbtiles file, which is included inside the app bundle itself? I am trying to achieve this on iOS.

I have checked Mapbox, but they offer only downloading areas through their manager, so no way to provide my own file.

I also checked https://github.com/klokantech/osm2vectortiles-ios-helloworld but data there still comes from web.

**Comment by klokan** [comment]
Contact info@klokantech.com if you want access to the source code of our native OSM2VectorTiles mobile app.
