### ISSUE TITLE
directions and rotate map

### ISSUE THREAD

**Issue by mnemonic-art** [klokan/osm-vector-offline#5]
Get directions on this map from point A to point B?
Is it possible to rotate the map automatically, for example using a compass?
Thanks!

**Comment by klokan** [comment]
We have switched to MapBox SDKs natively on Android and iOS.

See our sample app: OSM2VectorTiles (on AppStore / Google Play). You may get source code of the app from us.

Another our mobile app is now beeing ported to WebGL natively - with fallback to raster tiles for old mobile phones - made with http://blog.klokantech.com/2016/08/tileserver-gl-maps-with-gl-json-styles.html

Answers (valid for native open-source MapBox SDKs, not for the Cordova wrapper):

> Directions

Yes - with the official MapBox API and purchased plan.
On your own server (without MapBox plan) only if you install OSRM and implement an API and index the whole world or area of your interest from OpenStreetMap.

> Rotate the map automatically with compass

Yes. Possible.

If you need help - contact info@klokantech.com. We can provide commercial consulting.

Closing this ticket as there is no action to do for @klokantech team on this repository.
